### PR TITLE
add jetbldr-eu and jetbldr-ap

### PR DESCRIPTION
**Pull request by jetbldr**

### CODE REVIEW

**Comment by jetbldr** [comment]
@unclezoro Pls review this

**Comment by jetbldr** [comment]
hello @unclezoro, we double checked the rpc and updated the document, anything else to do?

**Comment by jetbldr** [comment]
@unclezoro ,  We have set up several BSC nodes for this MR. If it's inconvenient for you to provide a response in a short time, please let us know, and we will temporarily shut them down.

**Comment by jetbldr** [comment]
@unclezoro , any updates?

**Review by unclezoro — APPROVED** [review]

**Comment by unclezoro** [comment]
hi @jetbldr  can we have a TG connection where we can communicate efficiently

**Comment by jetbldr** [comment]
@unclezoro , our telegram account jetbldr_xyz

**Pull request merged**
